// Re-export all configs for convenience
export { base } from './base.js';
export { baseTypescript } from './base-typescript.js';
export { react } from './react.js';
export { reactLibrary } from './react-library.js';
export { reactLibraryJs } from './react-library-js.js';
export { nextjs } from './nextjs.js';
export { server } from './server.js';
export { nestjs } from './nestjs.js';
export { nodeLibrary } from './node-library.js';
export { nodeLibraryJs } from './node-library-js.js';
